# Generated by Django 3.2.15 on 2022-09-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_quantity',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='address',
            field=models.CharField(default='A-105', max_length=200),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='amount',
            field=models.FloatField(default='453.98'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='first_name',
            field=models.CharField(default='Vivek', max_length=200),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='last_name',
            field=models.CharField(default='Dhakad', max_length=200),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='mobile',
            field=models.BigIntegerField(default='9131592788'),
        ),
    ]
