# Generated by Django 3.2.15 on 2022-09-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20220902_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Vivek', max_length=200)),
                ('last_name', models.CharField(default='Dhakad', max_length=200)),
                ('address', models.CharField(default='NIL', max_length=200)),
                ('mobile', models.BigIntegerField(default='0000000000')),
                ('amount', models.FloatField(default='00.00')),
                ('customerCardNumber', models.BigIntegerField(default='0000000000000000')),
            ],
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
